name: Generate Snake & Pacman Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake and pacman SVG
        uses: Platane/snk@v3
        with:
          github_user_name: TharinduThilakshana0thildezo
          outputs: |
            ./output/github-snake.svg
            ./output/pacman-contribution-graph.svg?animation=pacman

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution graph"
          add: "output/*.svg"
